github.com:
    users:
        duphamgit:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: duphamgit
